language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

before_script:
  - rustup component add rustfmt
script:
  - cargo fmt --all -- --check
  - bin/test.sh

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
