language: rust
sudo: required

rust:
  - stable
  - beta
  - nightly


cache: cargo


before_script:
  - rustup component add rustfmt --toolchain $TRAVIS_RUST_VERSION 
  - cp fixtures/example.yaml rumake.yaml
  - git clone https://github.com/sstephenson/bats.git $HOME/bats && cd $HOME/bats && sudo ./install.sh /usr/local && cd -


script:
  - cargo check
  - cargo fmt --all -- --check
  - cargo test
  - tests/smoke.sh
  - tests/tasks.sh

env:
  global:
    - PROJECT_NAME=rumake
    - TARGET=x86_64-unknown-linux-gnu

before_deploy:
  - mkdir releases
  - cargo build --release --target=$TARGET
  - strip target/${TARGET}/release/${PROJECT_NAME}
  - tar czf releases/${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.tar.gz README.md -C target/${TARGET}/release/ ${PROJECT_NAME}

deploy:
  provider: releases
  api_key:
    secure: yIJ6jiYwjCjk3lVUIOeZcrcDTsjv+8suK/bpqRPW0lKDMtw8m89OJFNchIxY0eMmJ12HQDT0PuYafCOHV/HcJrDcepY8vyq0LSpgKrXv7pqmIHxRS0BQUfmJnIMRJKwyakwidtp5+tnlMMmtdJM5S1X+XVOmWMSFgw2nmm1s/viJ0/1FG0iR6XGhPeKUKoHtOMsQVQjR7j6iSjnnXvwHJVlAd/TdU15oBjGbi2hydjB3i1nO0cFozcqoKX2scu3E/gszR2HRnykv0Zu5KaKft7GOpF27ZA5bzsXRHKrCEbmFJ1+2zsG0/ube7aUj+TXOamYoFimgiIxXNxeNd6MSSxlh+bPnJBQskBt6VxZFM/EfHYEB+b30TiHAUkOFK4Wq1gZxvXZ+xIujn9M7ajImAN4F1zBQ8V3vsYqRpDvi3wSdfnUTPtQ0yZp+szJDQhZEkJRzp+ApbzPxuehsCxV6fnhnDqVZ/9sNB3PEzU+iG4cG7AO3T+ypx2AzwMWXWb3yaSO+5cVAmSbeBpRsl15agIjT/2YQ9hZQ+mVW/MiPYbV1WAYSul+nNIUWE0t/b8g/p0JBpv54IZggnStwYj6MXonlgFOb2MoWlGzsY221DSzZ6nGUo4uzSZi7Twhsm36y8du+3HUun9Ns9iBgng6s1SyqXsjAdSmm5uhRDEF9BUA=
  file: releases/${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.tar.gz
  on:
    condition: $TRAVIS_RUST_VERSION = nightly
    tags: true
  skip_cleanup: true
