language: rust
sudo: required

rust:
  - stable
  - beta
  - nightly


cache: cargo


before_script:
  - rustup component add rustfmt --toolchain $TRAVIS_RUST_VERSION 
  - cp fixtures/example.yaml rumake.yaml
  - git clone https://github.com/sstephenson/bats.git $HOME/bats && cd $HOME/bats && sudo ./install.sh /usr/local && cd -


script:
  - cargo check
  - cargo fmt --all -- --check
  - bin/test.sh
  - tests/tasks.sh


matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
