[package]
name = "rumake"
version = "0.1.0"
authors = ["tom <t.vitureau@purjus.fr>"]
edition = "2018"

[dependencies]
yaml-rust = "0.4"
linked-hash-map = "0.5"
regex = "1"
log = "0.4"
pretty_env_logger = "0.3"
shellwords = "1"
